Meteor.startup ->
	if Tournaments.find().count() is 0
		t1 = {
			name: "Grand Prix Gothenburg"
			startDate: new Date("2013-06-07")
			endDate: new Date("2013-06-09")
			format: "RTR Sealed"
			country: "se"
			type: "gp"
			finished: false
		}

		t2 = {
			name: "Grand Prix Providence"
			startDate: new Date("2013-06-07")
			endDate: new Date("2013-06-09")
			format: "RTR Sealed"
			country: "us"
			type: "gp"
			finished: false
		}

		t3 = {
			name: "Grand Prix Bangkok"
			startDate: new Date("2013-06-21")
			endDate: new Date("2013-06-23")
			format: "RTR Sealed"
			country: "th"
			type: "gp"
			finished: false
		}

		t4 = {
			name: "Grand Prix Calgary"
			startDate: new Date("2013-07-26")
			endDate: new Date("2013-07-28")
			format: "Standard"
			country: "ca"
			type: "gp"
			finished: false
		}

		t5 = {
			name: "Pro Tour Dragon's Maze"
			startDate: new Date("2013-05-17")
			endDate: new Date("2013-05-19")
			format: "RTR Block, Draft"
			country: "us"
			type: "pt"
			finished: true
			standings: [
				"Wescoe, Craig"
				"Castellon, Rob"
				"Mihara, Makihito"
				"Shrout, Andrew"
				"Utter-Leyton, Josh"
				"Zatlkaj, Matej"
				"Ochoa, Dusty"
				"Prost, Andrejs"
				"Duke, Reid"
				"Froehlich, Eric"
				"Scott-Vargas, Luis"
				"Martell, Tom"
				"Nassif, Gabriel"
				"Sharfman, David"
				"Fennell, Chris"
				"Cuenca, Nicolas"
				"Polak-Rottmann, Oliver"
				"Kibler, Brian"
				"Eilers, Mark"
				"Rachid, Denniz"
				"Swift, Orrin"
				"Yim, Chi Hoi"
				"Peleg, Uri"
				"Yukuhiro, Ken"
				"Borba, Rodrigo"
				"Bernat, Michael"
				"Holiday, Nathan"
				"Lax, Ari"
				"Aintrazi, Ali"
				"Swasey, Laurence"
				"Costa, Matthew"
				"Sullivan, Patrick"
				"Dupuy, Alejandro"
				"Juza, Martin"
				"Jurkovic, Robert"
				"Mann, Stephen"
				"Levy, Raphael"
				"Saito, Tomoharu"
				"Yamaguchi, Satoshi"
				"Chapin, Patrick"
				"Nakamura, Shuuhei"
				"Koestler, Jonas"
				"Dezani, Jeremy"
				"Chanpleng, Sethsilp"
				"Oberg, Kenny"
				"Edgerle, Nick"
				"Nordahl, Andreas"
				"Bertiou, Simon"
				"Fehr, Christian"
				"Faeder, Dustin"
				"Cox, Patrick"
				"Wang, Ming Chee"
				"Huang, Hao-Shan"
				"Pranoto, Andreas"
				"Tapia Becerra, Felipe"
				"Jensen, Marten"
				"Muller, Andre"
				"Pirouet, Ian"
				"Klump, Erik"
				"Silva, José Francisco"
				"Cifka, Stanislav"
				"Westling, Tomas"
				"van der Vegt, Jan"
				"DeTora, Melissa"
				"Nezin, Alec"
				"Behrens, Lance"
				"Stroev, Mikhail"
				"Oomori, Ken'ichirou"
				"Budde, Kai"
				"Hobler, Seneca"
				"Portaro, Alessandro"
				"Woods, Conley"
				"Shiraishi, Tomomi"
				"Brown, Alex"
				"Kurth, Lloyd"
				"Stefanescu, Alexandru"
				"Demars, Brian"
				"Nguyen, Richard"
				"Peng, Jianjia"
				"Skarren, Frank"
				"Cantillana, Andrew"
				"Lucy, J. Sawyer"
				"Veenis, Raymond"
				"Liu, Zhuoran"
				"Maher, Robert"
				"La Porta, Alessandro"
				"Bland, Richard"
				"Edwards, Kerry"
				"Ahlberg, Daniel"
				"Mowshowitz, Zvi"
				"Black, Samuel"
				"Merriam, Ross"
				"Nelson, Brad"
				"Vantuch, Mates"
				"Stern, Jon"
				"Kuo, Tzu-Ching"
				"Gushen, Dan"
				"Nass, Matthew"
				"Fehling, Patrick"
				"Potter, Doug"
				"Ravitz, Joshua"
				"Schneider, Andrew"
				"Jackson, Paul"
				"Dominguez Roldan, Fern"
				"Bernal, Joe"
				"Moreno Morales, Franci"
				"Stajic, Milos"
				"Zimmermann, Jonas"
				"Wiegersma, Jelger"
				"Bollati, matias"
				"Zulian, Simone"
				"Nakano, Yoshitaka"
				"Weigle, Sean"
				"Carleton-Barnes, Gabri"
				"de Jesus Freitas, Marc"
				"Wilson, Jacob"
				"Le Friant, Christopher"
				"Rolin, Christophe"
				"Adebo Diaz, Juan Carlo"
				"Nagy, Tamas"
				"Minard, Darin"
				"Lerro, Lorenzo"
				"Lewis, Aaron"
				"Shiels, Dave"
				"Monsalve, Andres"
				"Summersberger, Helmut"
				"Ikawa, Yoshihiko"
				"Friedman, Ben"
				"Bergström, Jonathan"
				"Ochoa, David"
				"Teneggi, Alessandro"
				"Laskin, Lewis"
				"Demestrio, Joe"
				"Kraft, René"
				"Khodasevich, Egor"
				"Estratti, samuele"
				"Kastle Mess, Darwin"
				"Christiansen, Nico"
				"Sixkiller, Gerald"
				"Van Etten, Bart"
				"Watanabe, Yuya"
				"Cheung, Justin"
				"Finkel, Jon"
				"Bonifacio, Vasco"
				"Jaklovsky, Lukas"
				"Marcucci, Federico"
				"Rizzi, Mattia"
				"Bjørnerud, Sveinung"
				"Dorsett, Zachariah"
				"Parson, Lukas"
				"Holzinger, Thomas"
				"Ramis Pascual, Toni"
				"Passow, Christopher"
				"Kornacki, Jon"
				"Schultze, Max"
				"Palacio, Jaime"
				"Neeman, Jeremy"
				"Glantzman, Joshua"
				"Vidugiris, Gaudenis"
				"Nagy, Ferenc"
				"Kitayama, Masaya"
				"Floch, Ivan"
				"Rodriguez, Javier"
				"Kaurinovic, Timmy"
				"Rodriguez, Jose R."
				"Hibino, Yasutaka"
				"Sabbadini, Massimo"
				"Hovanec, Wesley"
				"Horváth, Tamás"
				"Russo, Enrico"
				"Hadrys, Piotr"
				"Nagai, Mamoru"
				"Hartman, Reed"
				"Cuneo, Andrew"
				"Hampton, Jesse"
				"Hocquemiller, Arnaud"
				"Thompson, Gerry"
				"Nilsson, Andreas"
				"Abramowski, Scott"
				"Lippi, Alessandro"
				"Sele, Yves"
				"Kuisma, Matti"
				"Tsuchiya, Hiroki"
				"Wong, Wei Quan"
				"Pasqui, Giulio"
				"Giusti, Emanuele"
				"Vargas Carreras, Juan"
				"Loy, Samuel"
				"spanu, gianluca"
				"Dougherty, Robert"
				"Mengucci, Andrea"
				"Vincent, Guillaume"
				"Iyanaga, Jun'ya"
				"Kumagai, Riku"
				"Dela Cruz, Jimmy"
				"Hauck, Manuel"
				"Tickal, Matthew"
				"Tomiczek, Bartlomiej"
				"Snepvangers, Bram"
				"Ross, Jamie"
				"Chew, Kelvin"
				"Watsfeldt, Elias"
				"Harris, Colin"
				"Bazzana, Aaron"
				"Sigrist, Mike"
				"Yasooka, Shouta"
				"Stark, Ben"
				"Levy, Olivier"
				"Davis, Jim"
				"Flores, Edgar"
				"Unwin, Daniel"
				"Jordan, Dan"
				"Simonot, Timothée"
				"Caplan, David"
				"Berlingieri, Anthony"
				"Muller, Timothy"
				"Izsak, Yoel"
				"Filho, Walter"
				"Shenhar, Shahar"
				"Donegan, Dylan"
				"Cordero Valle, Marcos"
				"Motomura, Tomoya"
				"Roystan, Andrew"
				"Parker, Brock"
				"Edel, Willy"
				"Zimmermann, Raoul"
				"Bedsole, Hayden"
				"McClain, Josh"
				"Ruizi, Lin"
				"Johnson-Epstein, Jaspe"
				"Barraza, Eduardo"
				"Criado, Pablo"
				"Denno, Sebastian"
				"Park, Jun Young"
				"Damo da Rosa, Paulo Vi"
				"Crimin, Kevin"
				"De Haan, Rob"
				"Snook, Adam"
				"Lee, Alex"
				"Simard, Mark"
				"Lespinas, Didier"
				"Swiney, Michael"
				"Rinnen, Davide"
				"Wald, Piotr"
				"Truong, Duc"
				"Sergio, Martin"
				"Wiitanen, Joshua"
				"Gorokhovskyy, Kostyant"
				"Gryn, Maksym"
				"Zúñiga, Cristian"
				"Chiba, Akio"
				"Enevoldsen, Thomas"
				"Jones, Oscar"
				"Ganz, Andreas"
				"Sidher, Ricky"
				"Telarov, Aleksa"
				"Ichikawa, Yuuki"
				"Stihle, Julien"
				"Krasnitski, Mike"
				"Villela, Artur"
				"Lee, Shi Tian"
				"Hunt, Matthias"
				"Zhao, Tian Yu"
				"Takahashi, Yuuta"
				"Sim, Chapman"
				"Ishimura, Shintaro"
				"Malka, Ariel"
				"Holland, Joe"
				"Radloff, Tobias"
				"Jones, Kevin"
				"Alvarado, Saul"
				"Grendell, James"
				"Carlsson, Per"
				"Trnka, Dalibor"
				"Carlsson, Fredrik"
				"Tabak, Josh"
				"Magnusson, Mikael"
				"Jones, Alek"
				"Nolan, Timothy"
				"Ylioja, Ilkka-Aleksi"
				"Mundhenk, Jonas"
				"Nakamura, Atsushi"
				"Takagi, Takeshi"
				"Liu, Robert"
				"Goldfarb, Mat"
				"Betesh, Ralph"
				"Williams, David"
				"Zheng, Jingwei"
				"McLaren, Shaun"
				"Wijaya, Vidianto"
				"Anteri, Fabrizio"
				"Korff, Ruan"
				"Isgur, Benjamin"
				"Arsenault, Frederique"
				"Ortiz, Ottoniel"
				"Londos, Ludvig"
				"Pardee, Samuel"
				"Toledo, Daniel"
				"Costa-Giomi, Gabriel"
				"McLaren, Dean"
				"Hayne, Alexander"
				"Constant, Michael"
				"Baldasari, Antonino"
				"Versari, Matteo"
				"Belanger, Maxim"
				"Leete, Aaron"
				"Botoff, Daniel Neal"
				"Maguire, Doug"
				"Brendemühl, Bernd"
				"Takahashi, Zen"
				"Pilorget, Simon"
				"Dominguez Roldan, Alfr"
				"Sato, Shinya"
				"Leong, Ding"
				"Royde, Daniel"
				"Hartman, Christopher"
				"Tan, richmond"
				"Humbaraci, Alp"
				"Wen, Bernie"
				"Hickox, Tyler"
				"Rietzl, Paul"
				"Jacobs, Maarten"
				"Pedrakowski, Tomek"
				"Alkio, Anssi"
				"Ewenstein, Paul"
				"Rickarby, Thomas"
				"Stewart, Connor"
				"Humphreys, Richard"
				"Sjoblom, Max"
				"Sconci, Jacob"
				"Bennett, Gavin"
				"hames, James"
				"Egan, Isaac"
				"Pizzi, William"
				"Fang, Zhengyang"
				"Peters, Erik"
				"Arcos, Francisco"
				"Pérez, Asier"
				"Bergen, Wesley"
				"Turtenwald, Owen"
				"Pal, Carlos"
				"Meade, Nicholas"
				"Farreras, Gerard"
				"Kassis, Eli"
				"Berg, Jimmy"
				"Godoy Junior, Celso An"
				"Quinn, Andrew"
				"Ouimet, Guillaume"
				"Deltour, louis"
				"Morris, Anthony"
				"Curran, Trevor"
				"Tajak, Lukas"
				"Calcano, Christian"
				"Jesse, Zach"
				"Durward, Caleb"
				"Metzger, Jonathan"
				"Fatela, Yohan"
				"Ealey, Timothy"
				"Gonzales, Roberto"
				"Hessmiller, Gannon"
				"Real, Enzo"
				"West, Alexander"
				"Tukeman, Sammy"
				"Harada, Ryan"
				"Grosso, Francesco"
				"Rogasner, Gabriel"
				"Hall, Daniel"
				"Schmidt, Travis"
				"Manders, Mitchell"
				"Stegall, Chris"
				"Comminos, Bill"
				"Daniel, David"
				"Fabiano, Gerard"
				"Lee, Jackie"
				"Plott, Sean"
				"Froehlig, Timothy"
				"Snijdewind, Ruben"
				"Blum, Tyler"
				"Alimoglu, Emir"
				"Larsson, Joel"
				"Thompson, Troy"
				"Pesch, Ryan"
				"Giese, Sean"
				"Maynard, Pascal"
				"Miyashiro, Travis"
				"Horig, Wilfy"
				"Andersen, Oyvind Wefal"
			]
		}

		Tournaments.insert(t1);
		Tournaments.insert(t2);
		Tournaments.insert(t3);
		Tournaments.insert(t4);
		Tournaments.insert(t5);

		for player in t5.standings
			Players.insert { name: player }